import type { Account } from "@/types";

const accounts: Account[] = [
  {
    id: "acc-msp",
    name: "TTEC Computers",
    type: "MSSP",
    parentAccountId: null,
    parentAccountName: "Ingram Micro LP",
    status: "Paying",
    services: [
      { name: "Browser - Classic", status: "Active" },
      { name: "Email Security", status: "Active" },
      { name: "Mobile Security", status: "Active" },
    ],
    operationalIssues: 0,
    earliestContractExpiry: "2027-04-17",
    accountCreated: "2026-04-09",
    mainAdministratorEmail: "admin@ttec.com",
    seatsAllocated: 3000,
    seatsActive: 2418,
  },
  {
    id: "acc-1",
    name: "King Street Dentistry",
    type: "CUSTOMER",
    parentAccountId: "acc-msp",
    parentAccountName: "TTEC Computers",
    status: "Paying",
    services: [{ name: "Mobile Security", status: "Active" }],
    operationalIssues: 0,
    earliestContractExpiry: "2033-05-20",
    accountCreated: "2026-04-17",
    mainAdministratorEmail: "office@kingstreetdentistry.com",
    seatsAllocated: 25,
    seatsActive: 22,
  },
  {
    id: "acc-2",
    name: "ABC Corporation",
    type: "CUSTOMER",
    parentAccountId: "acc-msp",
    parentAccountName: "TTEC Computers",
    status: "Paying",
    services: [
      { name: "Email Security", status: "Active" },
      { name: "Browser - Classic", status: "Require Activation" },
    ],
    operationalIssues: 1,
    earliestContractExpiry: "2026-08-25",
    accountCreated: "2026-02-11",
    mainAdministratorEmail: "it@abccorp.com",
    seatsAllocated: 500,
    seatsActive: 470,
  },
  {
    id: "acc-3",
    name: "XYZ Ltd",
    type: "CUSTOMER",
    parentAccountId: "acc-msp",
    parentAccountName: "TTEC Computers",
    status: "Trial",
    services: [{ name: "Mobile Security", status: "Require Activation" }],
    operationalIssues: 0,
    earliestContractExpiry: "2026-09-01",
    accountCreated: "2026-07-15",
    mainAdministratorEmail: "admin@xyzltd.com",
    seatsAllocated: 50,
    seatsActive: 12,
  },
  {
    id: "acc-4",
    name: "Riverside Law Group",
    type: "CUSTOMER",
    parentAccountId: "acc-msp",
    parentAccountName: "TTEC Computers",
    status: "Suspended",
    services: [{ name: "Email Security", status: "Active" }],
    operationalIssues: 2,
    earliestContractExpiry: "2026-07-10",
    accountCreated: "2025-11-02",
    mainAdministratorEmail: "admin@riversidelaw.com",
    seatsAllocated: 120,
    seatsActive: 0,
  },
  {
    id: "acc-5",
    name: "Northgate Financial",
    type: "CUSTOMER",
    parentAccountId: "acc-msp",
    parentAccountName: "TTEC Computers",
    status: "Pending",
    services: [{ name: "Browser - Classic", status: "Require Activation" }],
    operationalIssues: 0,
    earliestContractExpiry: null,
    accountCreated: "2026-08-01",
    mainAdministratorEmail: "admin@northgatefinancial.com",
    seatsAllocated: 80,
    seatsActive: 0,
  },
];

export function listAccounts(): Account[] {
  return accounts;
}

export function getAccount(id: string): Account | undefined {
  return accounts.find((account) => account.id === id);
}
