import type { ClientOrganization } from "@/types";

const organizations: ClientOrganization[] = [
  {
    id: "acc-1",
    name: "King Street Dentistry",
    parentOrganizationId: "msp-1",
    parentOrganizationName: "TTEC Computers",
    status: "Paying",
    services: [{ name: "Mobile Security", status: "Active" }],
    operationalIssues: 0,
    earliestContractExpiry: "2033-05-20",
    createdAt: "2026-04-17",
    mainAdministratorEmail: "office@kingstreetdentistry.com",
    primaryContact: "Morgan Diaz",
    administrationMode: "Client Managed",
    seatsAllocated: 25,
    seatsActive: 22,
  },
  {
    id: "acc-2",
    name: "ABC Corporation",
    parentOrganizationId: "msp-1",
    parentOrganizationName: "TTEC Computers",
    status: "Paying",
    services: [
      { name: "Email Security", status: "Active" },
      { name: "Browser - Classic", status: "Require Activation" },
    ],
    operationalIssues: 1,
    earliestContractExpiry: "2026-08-25",
    createdAt: "2026-02-11",
    mainAdministratorEmail: "it@abccorp.com",
    primaryContact: "Priya Nair",
    administrationMode: "Client Managed",
    seatsAllocated: 500,
    seatsActive: 470,
  },
  {
    id: "acc-3",
    name: "XYZ Ltd",
    parentOrganizationId: "msp-1",
    parentOrganizationName: "TTEC Computers",
    status: "Trial",
    services: [{ name: "Mobile Security", status: "Require Activation" }],
    operationalIssues: 0,
    earliestContractExpiry: "2026-09-01",
    createdAt: "2026-07-15",
    mainAdministratorEmail: "admin@xyzltd.com",
    primaryContact: "Jamie Chen",
    administrationMode: "MSP Managed",
    seatsAllocated: 50,
    seatsActive: 12,
  },
  {
    id: "acc-4",
    name: "Riverside Law Group",
    parentOrganizationId: "msp-1",
    parentOrganizationName: "TTEC Computers",
    status: "Suspended",
    services: [{ name: "Email Security", status: "Active" }],
    operationalIssues: 2,
    earliestContractExpiry: "2026-07-10",
    createdAt: "2025-11-02",
    mainAdministratorEmail: "admin@riversidelaw.com",
    primaryContact: "Sam Patel",
    administrationMode: "MSP Managed",
    seatsAllocated: 120,
    seatsActive: 0,
  },
  {
    id: "acc-5",
    name: "Northgate Financial",
    parentOrganizationId: "msp-1",
    parentOrganizationName: "TTEC Computers",
    status: "Pending",
    services: [{ name: "Browser - Classic", status: "Require Activation" }],
    operationalIssues: 0,
    earliestContractExpiry: null,
    createdAt: "2026-08-01",
    mainAdministratorEmail: "admin@northgatefinancial.com",
    primaryContact: "Taylor Brooks",
    administrationMode: "MSP Managed",
    seatsAllocated: 80,
    seatsActive: 0,
  },
];

export function listClientOrganizations(): ClientOrganization[] {
  return organizations;
}

export function getClientOrganization(id: string): ClientOrganization | undefined {
  return organizations.find((organization) => organization.id === id);
}
